### ISSUE TITLE
Connectivity issue with connection to NCBI when using get_dbcan_cazymes

### ISSUE THREAD

**Issue by PeterMBlack** [HobnobMancer/cazomevolve#23]
Error occurs when trying to retrieve the tax ids from NCBI for adding taxonomic information to the 2 output tab delimited lists when running the get_dbcan_cazymes command on the St Andrews Kennedy Supercluster. 

Output slurm log file (timed out after 24hrs): [slurm-232789.out.txt](https://github.com/HobnobMancer/cazomevolve/files/14422795/slurm-232789.out.txt)

Slurm script used to run this analysis: [AnnotateCazomesLargerGroup250224.sh.txt](https://github.com/HobnobMancer/cazomevolve/files/14422821/AnnotateCazomesLargerGroup250224.sh.txt)

(Also included is the output for cazomevolve run_dbcan, which has a code future proofing warning for extracting the values from the dbcan overview.txt file for each of the tools which may cause a future issue)

**Comment by HobnobMancer** [comment]
Issue should be fixed with `cazy_webscraper` >= 2.3.0.3
